apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "k8s-webhook.licious.com"
webhooks:
- name: "k8s-webhook.licious.com"
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - default
          - k8s-webhook
          - monitoring
          - observability
          - kafka-dp-cluster
          - emissary-system
          - spark-operator
          - sigtest
          - clickhouse
          - platform
          - k8ssandra
          - pl
          - vault
          - teamcity
          - l3-opentemetry

  rules:
  - apiGroups: ["*"]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["deployments"]
    scope: "Namespaced"
  clientConfig:
    service:
      namespace: k8s-webhook
      name: k8s-webhook
      path: /mutate-deployment
      port: 8080
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lVZldDUmsyUlJGN3d3R0tnY1FBdENvc1dxTlU4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0l6RUxNQWtHQTFVRUJoTUNRVlV4RkRBU0JnTlZCQU1NQzJzNGN5MTNaV0pvYjI5ck1CNFhEVEkwTURNeApOREEyTWpjME1sb1hEVEkxTURNeE5EQTJNamMwTWxvd0l6RUxNQWtHQTFVRUJoTUNRVlV4RkRBU0JnTlZCQU1NCkMyczRjeTEzWldKb2IyOXJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW5na2wKMTNvTVRjVThLelNEYjFtV0lPSFgrWmpxNEd1V25oTElLRUxOYzIyRVZ1Z2xKY1ZYbmJMRlhLdzVKb2wrS2ZkYQpBYkhqRXMxa3pVR3VpN2lZcWFaVFo0UDJGcHRxVTZaVnhKa1lTbFV0cUlVTEFkamZjRmtERHExN0JROXFwRzNNCk5NdXhDVDhrMy8xQm1nQURzK2xya1BjTHFTK1pzNmRWc0hiUlNBemlaVnRaWjlsZ1EyUVpCSlQ2THRUbVozZTUKRHR0RmZCMDRUNlVvVW9lL2E1V0R1bjhwMHBKK3NVNTQ1ZW5peTZsRHhNVmY1SFRITGUrK1E4MEY2MnFUOVMrWQpvY05keXUrRUNubjQrVDRtWGFKbDdIUWM3Ty9JUUhxQ0NrcWt6NXhWSXBMY29wQ1FvWmlhT2psb2FGaUVyNFJ4CnF6Q3dTUFVnem5RRWs2eGltUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVczlDWEJmS2FQanRBWlVOTmJJejMKVHRxazNCb3dId1lEVlIwakJCZ3dGb0FVczlDWEJmS2FQanRBWlVOTmJJejNUdHFrM0Jvd0R3WURWUjBUQVFILwpCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtZFV5aTJSSEhzVEpKOUovVThSalc0d1pxQmdQClJ4K05leHRtQVhubTdnR3BUU0pKTC9yamdvbjVCc2RBemFEZTBKZEFJNWlpbDFEdWJuQXlWUVN2SlNRbzRaWSsKV2hTTVhqOUlJYk9JcDM0SW0ySDBHTks4ZXZkTGVTdWplOElieWh5THhMcDJpeXJlRnBlTVB5VGZGUENxWlNCRwpZTTJVSlIyS0REelBFRVh2SkRQZ2lwbmZzaVNNWjZBMFoxSXh3WTYrL1Myb1hMSHJtOXZuRUxlek5YWmE2dTBaCmt4MkJPZ0tmK3kwTW0wMUpqZmJHMytxSnNKeVNJclo4azRFRjc5dEhmWGVkU2dqcXViVTdhSzJMMElXVDJtYloKNVA5cHBRL2tHL0JVejVOTzZoYXNRUTZ2VTBGOVQvOTdDSWtqejF4UHAxZGpJdFp2VHMrc2YwWlVCZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 2